language: php
php:
- '5.4'
install:
- sh travis.sh
script:
- sh run.sh
deploy:
  provider: releases
  api_key:
    secure: Zx/ocy8o9bB0nGVV81/qflEuN1wvqCwGP6Lei+ngCwgp7SwkwypjYcWemA8W1goTGkEQan4C4fdZvNgARyrO9/xUUt5sHn0yp5bsVWdPLpm7gEZRUzdsLscHLyig/+pPnQitZk08xHz8+mwqWSvfi2U8SZMmzYw6P0x94bPaaYjHg2MtUW8ijngGK+/CpgItKZGFDhUNfbXdx7KctSdB0S+AoX/+bpuifqw0wsWg+TBqFoqG5RY1xRgpxKhCvqu+aa2rQj4+XLwugtJq8NYlBPUfpjLY4ASml5+HsSy6Q+Za/OUuIRFdDF29CznqTPkbt0oA5hxqmEDFW3U5NpYt0iAjtFGE3SnQJJcokUKSCJFzbvLjecsX7iJx5oX73VjTUa8oM090gzOClz4lHnOMNx85zXgu7jYRMhmOImgv0CoFUc17/+hCVAXkH+Md8TDRPp9/NFpaUVZViidHlI+SCdAHl338Qm3ccVCVZSomHI1DrBY0QKrx25TrdpSTBGafa/SaXCHeV9eYf6xGOHOhY8F9kc5yjhl2snz/RDgdYoAGGkt8fgVc0GUIYi7HF34A5LbT2w8C8Tv/w55RBaDlamTH8x60/xeqbUeq4bT/YtXpCbWweiOeZcSOhW+p9zAwn+teCqV4G7Mf17WLQUK3oSKTvvw9WYBrnpGzCftU+OY=
  file: dokuwiki-docset.tgz
  skip_cleanup: true
  on:
    repo: gamma/dokuwiki-dash-docset
    tags: true
