language: php
php:
- '5.4'
install:
- sh travis.sh
script:
- sh run.sh
deploy:
  provider: releases
  api_key:
    secure: UkPXFMywsY5g6HuTXyW54ZpCG/ancbsmO21qhtKZIOobSc+fM1+7Ka34DJNIpPhAqhkmeE4ctEmO4Yf21AEetdDi45VGqtUXSXeMGmaxXUUwlcmAjedsSPlxaSUd3VIYQ72EGCq6svtwocIWfe7XiI6MbIxDAIqgBh2WL/DeauSQxZ/GOiPEflfh1qvQtthxg3eT8ZxbtHmPiJZ4Pu1yKn0YtECwhi2hcNxG7w5Dn8cYVOHP6EDYqzJGWthbIIlgWKRgXMnDZiLTayCxbpffzF8alE4QXhghn1s3d7BzL9An1SAaiwcUpnwQvCle7z8ab1ZWLJ73MOZPuWpJoGgIvvOkht1GOcWY/zdJoRUiZNu1qhBTfLqpKwTDv3Alw+11mG53pRhLpucQk8Hg2vdKB26SAkitwxutWNgqBANXNVg93Z4iDkttKNjxTDA0kTRoJPoYqHs2xFDdbiUKt7zRbEGKitDDZVZA0gBEiRbalu14Ay1kLKbVmBImL2t1945em5z7s2V9SISI7a1/ZGrBl5Wrhnz2HqN0VzWVwpXo+7DEYffyTyKXVWbVBMIxR+QrMvYPps4YMbl1dA7Q67ld15TJon5taLV0U99tiRELR6JugtZisYQ3WKysU5mhGKTIm1KFobsW60Vs5dXeYoD30WFSq1IQTrnQlNj8p1oog2s=
  file: dokuwiki-docset.tgz
  on:
    repo: gamma/dokuwiki-dash-docset
    tags: true
