language: php
php:
- '5.6'
env:
- DOKUWIKI=release_stable_2020-07-29
install:
- sh travis.sh
script:
- sh run.sh
deploy:
  provider: releases
  api_key:
    secure: $RELEASE_KEY
  file: dokuwiki-docset.tgz
  on:
    repo: gamma/dokuwiki-dash-docset
    tags: true
  skip_cleanup: 'true'
